# Generated by Django 2.2.19 on 2021-03-09 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='date_reserve',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='date_start',
            field=models.DateField(),
        ),
    ]
