# Generated by Django 2.2.19 on 2021-03-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cod_int', models.CharField(max_length=255)),
                ('user_in_charge', models.CharField(max_length=255)),
                ('max_people', models.IntegerField()),
                ('has_phone', models.BooleanField(default=False)),
                ('has_bathroom', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
            ],
        ),
    ]
